CREATE TABLE IF NOT EXISTS mocktest_passages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  passage_text TEXT NOT NULL,
  test_name TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);